# Generated by Django 4.0.4 on 2022-05-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificados', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('tituloInicial', models.CharField(blank=True, max_length=100, verbose_name='Título')),
                ('subTituloInicial', models.CharField(blank=True, max_length=100, verbose_name='SubTítulo')),
            ],
            options={
                'verbose_name': 'Pagina Inicial',
                'verbose_name_plural': 'Paginas Iniciais',
            },
        ),
    ]
