# Generated by Django 4.0.4 on 2022-05-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMenuPrincipal', '0002_paginainicial_pontoscamadas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paginainicial',
            name='pontosCamadas',
            field=models.CharField(blank=True, max_length=100, verbose_name='PontosCamadas'),
        ),
    ]
