# Generated by Django 4.0.4 on 2022-05-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMenuPrincipal', '0003_alter_paginainicial_pontoscamadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paginainicial',
            name='pontosCamadas',
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='pontosCamadasTitulo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pontos Camadas'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='primeiroPonto',
            field=models.CharField(blank=True, max_length=100, verbose_name='Primeiro ponto'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='quintoPonto',
            field=models.CharField(blank=True, max_length=100, verbose_name='Quinto ponto'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='terceiroPonto',
            field=models.CharField(blank=True, max_length=100, verbose_name='Segundo ponto'),
        ),
    ]
