# Generated by Django 4.0.4 on 2022-05-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMenuPrincipal', '0004_remove_paginainicial_pontoscamadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginainicial',
            name='descrisaoPontos',
            field=models.CharField(blank=True, max_length=100, verbose_name='Descrisão dos pontos'),
        ),
    ]
