# Generated by Django 4.0.4 on 2022-05-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMenuPrincipal', '0005_paginainicial_descrisaopontos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paginainicial',
            name='descrisaoPontos',
            field=models.CharField(blank=True, max_length=400, verbose_name='Descrisão dos pontos'),
        ),
    ]
