# Generated by Django 4.0.4 on 2022-05-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMenuPrincipal', '0007_alter_paginainicial_descrisaopontos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paginainicial',
            name='pontosCamadasTitulo',
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='pontosTitulo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pontos titulo sessão 2'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='primeiraDescrisao',
            field=models.CharField(blank=True, max_length=800, verbose_name='Primeira descrisão'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='primeiroTitulo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Primeiro titulo sessão 3'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='segundaDescrisao',
            field=models.CharField(blank=True, max_length=800, verbose_name='Segunda descrisão'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='segundoTitulo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Segundo titulo'),
        ),
    ]
