# Generated by Django 4.0.4 on 2022-05-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMenuPrincipal', '0010_paginainicial_primeirotopico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginainicial',
            name='descrisaoPrincipal',
            field=models.CharField(blank=True, max_length=800, verbose_name='Descrisão principal'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='subtituloSuperior',
            field=models.CharField(blank=True, max_length=100, verbose_name='Subtitulo superior (sessão 5)'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='tituloQuintaSessao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='paginainicial',
            name='pontosTitulo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pontos titulo (sessão 2)'),
        ),
        migrations.AlterField(
            model_name='paginainicial',
            name='primeiroTitulo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Primeiro titulo (sessão 3)'),
        ),
        migrations.AlterField(
            model_name='paginainicial',
            name='segundoTitulo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Segundo titulo (sessão 4)'),
        ),
        migrations.AlterField(
            model_name='paginainicial',
            name='tituloInicial',
            field=models.CharField(blank=True, max_length=100, verbose_name='titulo (sessão 1)'),
        ),
    ]
