# Generated by Django 4.0.4 on 2022-05-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMenuPrincipal', '0012_paginainicial_botaoquintasessao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginainicial',
            name='botaoSextaSessao',
            field=models.CharField(blank=True, max_length=80, verbose_name='Botão'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='primeiraDescrisaoSextaSesssao',
            field=models.CharField(blank=True, max_length=400, verbose_name='Primeira descrisão'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='primeiroSubtituloSextaSessao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Primeiro subtitulo'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='quartaDescrisaoSextaSesssao',
            field=models.CharField(blank=True, max_length=400, verbose_name='Quarta descrisão'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='quartoSubtituloSextaSessao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Quarto subtitulo'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='segundaDescrisaoSextaSesssao',
            field=models.CharField(blank=True, max_length=400, verbose_name='Segunda descrisão'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='segundoSubtituloSextaSessao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Segundo subtitulo'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='terceiraDescrisaoSextaSesssao',
            field=models.CharField(blank=True, max_length=400, verbose_name='Terceira descrisão'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='terceiroSubtituloSextaSessao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Terceiro subtitulo'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='tituloPrincipalSextaSessao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Titulo principal (sesssão 6)'),
        ),
    ]
