# Generated by Django 4.0.4 on 2022-05-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMenuPrincipal', '0013_paginainicial_botaosextasessao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginainicial',
            name='primeiroTituloCardSetimaSessao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Titulo do primeiro card'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='segundoTituloCardSetimaSessao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Titulo do segundo card'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='subtituloSuperiorSetimaSessao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Subtitulo superior (sessão 7)'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='terceiroTituloCardSetimaSessao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Titulo do terceiro card'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='tituloPrincipalSetimaSessao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Titulo principal'),
        ),
    ]
