# Generated by Django 4.0.4 on 2022-05-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMenuPrincipal', '0014_paginainicial_primeirotitulocardsetimasessao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginainicial',
            name='botaoOitavaSessao',
            field=models.CharField(blank=True, max_length=80, verbose_name='Botão'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='descrisaoOitavaSessao',
            field=models.CharField(blank=True, max_length=800, verbose_name='Descrisão principal'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='subtituloSuperiorOitavaSessao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Subtitulo superior (sessão 8)'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='tituloPrincipalOitavaSessao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Titulo principal'),
        ),
    ]
