# Generated by Django 4.0.4 on 2022-05-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMenuPrincipal', '0015_paginainicial_botaooitavasessao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginainicial',
            name='emailNonaSessao',
            field=models.CharField(blank=True, max_length=150, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='enderecoNonaSessao',
            field=models.CharField(blank=True, max_length=800, verbose_name='Endereço (sessão 9)'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='numeroNonaSessao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numero de contato'),
        ),
    ]
