# Generated by Django 4.0.4 on 2022-05-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMenuPrincipal', '0017_paginainicial_copyrightrodape_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginainicial',
            name='descrisaoPrimeiroCardSetimaSessao',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descrisao do primeiro card'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='descrisaoSegundoCardSetimaSessao',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descrisao do segundo card'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='descrisaoterceiroCardSetimaSessao',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descrisao do terceiro card'),
        ),
    ]
