# Generated by Django 4.0.4 on 2022-05-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMenuPrincipal', '0018_paginainicial_descrisaoprimeirocardsetimasessao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginainicial',
            name='primeiraOpcao',
            field=models.CharField(blank=True, max_length=100, verbose_name='titulo (sessão 1)'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='quartaOpcao',
            field=models.CharField(blank=True, max_length=100, verbose_name='titulo (sessão 1)'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='quintaOpcao',
            field=models.CharField(blank=True, max_length=100, verbose_name='titulo (sessão 1)'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='segundaOpcao',
            field=models.CharField(blank=True, max_length=100, verbose_name='titulo (sessão 1)'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='sextaOpcao',
            field=models.CharField(blank=True, max_length=100, verbose_name='titulo (sessão 1)'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='terceiraOpcao',
            field=models.CharField(blank=True, max_length=100, verbose_name='titulo (sessão 1)'),
        ),
        migrations.AddField(
            model_name='paginainicial',
            name='ultimoBotao',
            field=models.CharField(blank=True, max_length=100, verbose_name='titulo (sessão 1)'),
        ),
    ]
