# Generated by Django 4.0.4 on 2022-05-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMenuPrincipal', '0019_paginainicial_primeiraopcao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paginainicial',
            name='primeiraOpcao',
            field=models.CharField(blank=True, max_length=100, verbose_name='1º (Barra de navegação)'),
        ),
        migrations.AlterField(
            model_name='paginainicial',
            name='quartaOpcao',
            field=models.CharField(blank=True, max_length=100, verbose_name='4º'),
        ),
        migrations.AlterField(
            model_name='paginainicial',
            name='quintaOpcao',
            field=models.CharField(blank=True, max_length=100, verbose_name='5º'),
        ),
        migrations.AlterField(
            model_name='paginainicial',
            name='segundaOpcao',
            field=models.CharField(blank=True, max_length=100, verbose_name='2º'),
        ),
        migrations.AlterField(
            model_name='paginainicial',
            name='sextaOpcao',
            field=models.CharField(blank=True, max_length=100, verbose_name='6º'),
        ),
        migrations.AlterField(
            model_name='paginainicial',
            name='terceiraOpcao',
            field=models.CharField(blank=True, max_length=100, verbose_name='3º'),
        ),
        migrations.AlterField(
            model_name='paginainicial',
            name='ultimoBotao',
            field=models.CharField(blank=True, max_length=100, verbose_name='7º'),
        ),
    ]
