# Generated by Django 4.0.4 on 2022-06-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMenuPrincipal', '0022_alter_segundasessão_descrisaopontos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segundasessão',
            name='descrisaoPontos',
            field=models.CharField(blank=True, max_length=800, verbose_name='Descrisão dos pontos'),
        ),
    ]
