# Generated by Django 4.0.4 on 2022-06-09 14:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteMenuPrincipal', '0023_alter_segundasessão_descrisaopontos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segundasessão',
            name='descrisaoPontos',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Descrisão dos pontos'),
        ),
    ]
