# Generated by Django 4.0.4 on 2022-06-23 12:09

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMenuPrincipal', '0024_alter_segundasessão_descrisaopontos'),
    ]

    operations = [
        migrations.AddField(
            model_name='parteinicial',
            name='imagemFundoPrincipal',
            field=stdimage.models.StdImageField(default=1, upload_to='', verbose_name='imagemFundoImagem de fundo principal'),
            preserve_default=False,
        ),
    ]
