# Generated by Django 4.0.4 on 2022-06-23 12:10

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMenuPrincipal', '0025_parteinicial_imagemfundoprincipal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parteinicial',
            name='imagemFundoPrincipal',
            field=stdimage.models.StdImageField(blank=True, upload_to='', verbose_name='imagemFundoImagem de fundo principal'),
        ),
    ]
