# Generated by Django 4.0.4 on 2022-06-23 12:29

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMenuPrincipal', '0026_alter_parteinicial_imagemfundoprincipal'),
    ]

    operations = [
        migrations.AddField(
            model_name='barradenavegação',
            name='logoNav',
            field=stdimage.models.StdImageField(blank=True, upload_to='', verbose_name='Logo da barra de navegação'),
        ),
        migrations.AddField(
            model_name='nonasessão',
            name='logoInferior',
            field=stdimage.models.StdImageField(blank=True, upload_to='', verbose_name='Logo inferior'),
        ),
        migrations.AddField(
            model_name='oitavasessão',
            name='imagemDoVideo',
            field=stdimage.models.StdImageField(blank=True, upload_to='', verbose_name='Imagem para o video'),
        ),
        migrations.AddField(
            model_name='parteinicial',
            name='slider1Principal',
            field=stdimage.models.StdImageField(blank=True, upload_to='', verbose_name='imagemFundoImagem da primeira caixa flutuante'),
        ),
        migrations.AddField(
            model_name='parteinicial',
            name='slider2Principal',
            field=stdimage.models.StdImageField(blank=True, upload_to='', verbose_name='imagemFundoImagem da segunda caixa flutuante'),
        ),
        migrations.AddField(
            model_name='quartasessão',
            name='imagemDireita',
            field=stdimage.models.StdImageField(blank=True, upload_to='', verbose_name='Imagem na direita'),
        ),
        migrations.AddField(
            model_name='quintasessão',
            name='icon1',
            field=stdimage.models.StdImageField(blank=True, upload_to='', verbose_name='Primeiro icone'),
        ),
        migrations.AddField(
            model_name='quintasessão',
            name='icon2',
            field=stdimage.models.StdImageField(blank=True, upload_to='', verbose_name='Segundo icone'),
        ),
        migrations.AddField(
            model_name='quintasessão',
            name='icon3',
            field=stdimage.models.StdImageField(blank=True, upload_to='', verbose_name='Terceiro icone'),
        ),
        migrations.AddField(
            model_name='quintasessão',
            name='icon4',
            field=stdimage.models.StdImageField(blank=True, upload_to='', verbose_name='Quarto icone'),
        ),
        migrations.AddField(
            model_name='quintasessão',
            name='icon5',
            field=stdimage.models.StdImageField(blank=True, upload_to='', verbose_name='Quinto icone'),
        ),
        migrations.AddField(
            model_name='quintasessão',
            name='imagemDireita',
            field=stdimage.models.StdImageField(blank=True, upload_to='', verbose_name='Imagem na direita'),
        ),
        migrations.AddField(
            model_name='sextasessão',
            name='imagemPrincipal',
            field=stdimage.models.StdImageField(blank=True, upload_to='', verbose_name='Imagem principal'),
        ),
        migrations.AddField(
            model_name='terceirasessão',
            name='imagemEsquerda',
            field=stdimage.models.StdImageField(blank=True, upload_to='', verbose_name='Imagem na esquerda'),
        ),
    ]
