# Generated by Django 4.0.4 on 2022-06-28 11:08

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMenuPrincipal', '0027_barradenavegação_logonav_nonasessão_logoinferior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barradenavegação',
            name='logoNav',
            field=stdimage.models.StdImageField(blank=True, upload_to='logo', verbose_name='Logo da barra de navegação'),
        ),
        migrations.AlterField(
            model_name='nonasessão',
            name='logoInferior',
            field=stdimage.models.StdImageField(blank=True, upload_to='logo', verbose_name='Logo inferior'),
        ),
        migrations.AlterField(
            model_name='oitavasessão',
            name='imagemDoVideo',
            field=stdimage.models.StdImageField(blank=True, upload_to='sessao8', verbose_name='Imagem para o video'),
        ),
        migrations.AlterField(
            model_name='parteinicial',
            name='imagemFundoPrincipal',
            field=stdimage.models.StdImageField(blank=True, upload_to='imgs inciais', verbose_name='imagemFundoImagem de fundo principal'),
        ),
        migrations.AlterField(
            model_name='parteinicial',
            name='slider1Principal',
            field=stdimage.models.StdImageField(blank=True, upload_to='imgs inciais', verbose_name='imagemFundoImagem da primeira caixa flutuante'),
        ),
        migrations.AlterField(
            model_name='parteinicial',
            name='slider2Principal',
            field=stdimage.models.StdImageField(blank=True, upload_to='imgs inciais', verbose_name='imagemFundoImagem da segunda caixa flutuante'),
        ),
        migrations.AlterField(
            model_name='quartasessão',
            name='imagemDireita',
            field=stdimage.models.StdImageField(blank=True, upload_to='sessao4', verbose_name='Imagem na direita'),
        ),
        migrations.AlterField(
            model_name='quintasessão',
            name='icon1',
            field=stdimage.models.StdImageField(blank=True, upload_to='icons', verbose_name='Primeiro icone'),
        ),
        migrations.AlterField(
            model_name='quintasessão',
            name='icon2',
            field=stdimage.models.StdImageField(blank=True, upload_to='icons', verbose_name='Segundo icone'),
        ),
        migrations.AlterField(
            model_name='quintasessão',
            name='icon3',
            field=stdimage.models.StdImageField(blank=True, upload_to='icons', verbose_name='Terceiro icone'),
        ),
        migrations.AlterField(
            model_name='quintasessão',
            name='icon4',
            field=stdimage.models.StdImageField(blank=True, upload_to='icons', verbose_name='Quarto icone'),
        ),
        migrations.AlterField(
            model_name='quintasessão',
            name='icon5',
            field=stdimage.models.StdImageField(blank=True, upload_to='icons', verbose_name='Quinto icone'),
        ),
        migrations.AlterField(
            model_name='quintasessão',
            name='imagemDireita',
            field=stdimage.models.StdImageField(blank=True, upload_to='sessao5', verbose_name='Imagem na direita'),
        ),
        migrations.AlterField(
            model_name='sextasessão',
            name='imagemPrincipal',
            field=stdimage.models.StdImageField(blank=True, upload_to='sessao6', verbose_name='Imagem principal'),
        ),
        migrations.AlterField(
            model_name='terceirasessão',
            name='imagemEsquerda',
            field=stdimage.models.StdImageField(blank=True, upload_to='sessao3', verbose_name='Imagem na esquerda'),
        ),
    ]
