# Generated by Django 4.0.4 on 2022-06-28 11:52

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMenuPrincipal', '0029_iconsquintasessão_remove_quintasessão_icon1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iconsquintasessão',
            name='imagemDireita',
        ),
        migrations.AddField(
            model_name='quintasessão',
            name='imagemDireita',
            field=stdimage.models.StdImageField(blank=True, upload_to='sessao5', verbose_name='Imagem na direita'),
        ),
    ]
